// ECE:3350 SISC processor project
// main SISC module, part 2
// I'm in your code - Andrew

`timescale 1ns/100ps  

module sisc (clk, rst_f);

  input clk, rst_f;

  // ir is now an internal wire driven by the IR module instead of an input
  wire [31:0] ir;

  // declare all internal wires here
  wire rf_we;              // register file write enable
  wire wb_sel;             // writeback mux select
  wire [3:0] alu_op;       // selects ALU operation
  wire [31:0] rsa;         // source register A value read from the register file
  wire [31:0] rsb;         // source register B value read from the register file
  wire [31:0] alu_result;  // ALU output
  wire [31:0] write_data;  // Data presented to the register file write_data input
  wire [3:0] alu_stat;     // New status bits generated by the ALU
  wire [3:0] stat_en;      // Per-bit enable lines for updating the status register
  wire [3:0] stat_out;     // Current status register output

  // part 2 wires
  wire [15:0] pc_out;      // program counter output
  wire [15:0] br_addr;     // branch address from BR module
  wire [31:0] read_data;   // instruction data from IM module
  wire br_sel;             // branch select (absolute vs relative)
  wire pc_rst;             // program counter reset
  wire pc_write;           // program counter write enable
  wire pc_sel;             // program counter input select
  wire ir_load;            // instruction register load enable


  // component instantiation goes here

  // part 2 modules
  pc  my_pc  (clk, br_addr, pc_sel, pc_write, pc_rst, pc_out);
  im  my_im  (pc_out, read_data);
  ir  my_ir  (clk, ir_load, read_data, ir);
  br  my_br  (pc_out, ir[15:0], br_sel, br_addr);

  // part 1 modules (ctrl updated with new port list for part 2)
  ctrl my_ctrl (clk, rst_f, ir[31:28], ir[27:24], stat_out, rf_we, alu_op, wb_sel, br_sel, pc_rst, pc_write, pc_sel, ir_load);
  rf my_rf (clk, ir[19:16], ir[15:12], ir[23:20], write_data, rf_we, rsa, rsb);
  alu my_alu (clk, rsa, rsb, ir[15:0], stat_out[3], alu_op, ir[27:24], alu_result, alu_stat, stat_en);
  statreg my_statreg (clk, alu_stat, stat_en, stat_out);
  mux32 my_mux (alu_result, 32'h00000000, wb_sel, write_data);


  initial begin
  
// put a $monitor statement here.  Updated for part 2 to include PC, BR_SEL, PC_WRITE, PC_SEL
    $monitor($time," IR=%h PC=%h R1=%h R2=%h R3=%h ALU_OP=%h BR_SEL=%b PC_WRITE=%b PC_SEL=%b",
             ir,
             pc_out,
             my_rf.ram_array[1],
             my_rf.ram_array[2],
             my_rf.ram_array[3],
             alu_op,
             br_sel,
             pc_write,
             pc_sel);
  end

endmodule