// ECE:3350 SISC processor project
// Paul Sullivan, Daniel Marshall

`timescale 1ns/100ps

module sisc (clk, rst_f);

  /* In part 2 the testbench only drives the clock and reset lines.
     The processor now fetches its own instructions from memory using
     the im, ir, and pc modules, so IR is no longer an external input. */

  input clk, rst_f; // clock signal and active-low reset

// declare all internal wires here

  // Part 1 wires, carried forward exactly as before
  wire rf_we;              // register file write enable
  wire wb_sel;             // writeback mux select
  wire [3:0] alu_op;       // selects the ALU operation to perform
  wire [31:0] rsa;         // source register A value read from the register file
  wire [31:0] rsb;         // source register B value read from the register file
  wire [31:0] alu_result;  // latched output of the ALU
  wire [31:0] write_data;  // data going into the register file write port
  wire [3:0] alu_stat;     // raw status bits generated by the ALU this cycle
  wire [3:0] stat_en;      // per-bit enables that control which status bits get saved
  wire [3:0] stat_out;     // current saved value of the status register

  // Part 2 wires, new signals that connect the fetch and branch hardware
  wire ir_load;            // tells the IR when to latch a new instruction
  wire pc_write;           // tells the PC when to save its next value
  wire pc_sel;             // chooses between PC+1 and the branch target address
  wire pc_rst;             // resets the PC to 0x0000 while the processor is in reset
  wire br_sel;             // chooses between relative and absolute branch mode
  wire [31:0] instr;       // the current 32-bit instruction, output of the IR
  wire [15:0] pc_out;      // current value of the program counter
  wire [15:0] br_addr;     // branch target address computed by the br module
  wire [31:0] im_data;     // raw 32-bit instruction word coming out of instruction memory

// component instantiation goes here

	/* We use names like u1 u2 u3 u4 so that the autograder understands the connections. Otherwise we would use 
	more interesting names. */

  ctrl u1 (clk, rst_f, instr[31:28], instr[27:24], stat_out,  // inputs to the control unit
           rf_we, alu_op, wb_sel,                              // part 1 outputs from ctrl
           ir_load, pc_write, pc_sel, pc_rst, br_sel);         // part 2 outputs from ctrl

  rf u2 (clk, instr[19:16], instr[15:12], instr[23:20], write_data, rf_we, rsa, rsb);

  alu u3 (clk, rsa, rsb, instr[15:0], stat_out[3], alu_op, instr[27:24], alu_result, alu_stat, stat_en);

  statreg u4 (clk, alu_stat, stat_en, stat_out); // saves ALU status flags for use in branches

  mux32 u5 (alu_result, 32'h00000000, wb_sel, write_data); // sel=0 picks alu_result

  im u6 (pc_out, im_data); // reads a 32-bit instruction from the address the PC is pointing to

  /* The branch unit gets pc_out, which is already PC+1 after the fetch state.
     For relative branches it computes (PC+1) + imm. For absolute branches
     br_sel forces the base to zero so the result is just the immediate value. */
  br u7 (pc_out, instr[15:0], br_sel, br_addr); // computes the branch target address

  ir u9 (clk, ir_load, im_data, instr); // latches the instruction from memory when ir_load is high

  pc u10 (clk, br_addr, pc_sel, pc_write, pc_rst, pc_out); // holds and updates the program counter


  initial begin

// Part 2 required monitor signals: IR, PC, R1, R2, R3, R4, ALU_OP, BR_SEL, PC_WRITE, PC_SEL
    $monitor($time," IR=%h PC=%h R1=%h R2=%h R3=%h R4=%h ALU_OP=%h BR_SEL=%b PC_WRITE=%b PC_SEL=%b",
             instr,
             pc_out,
             u2.ram_array[1],
             u2.ram_array[2],
             u2.ram_array[3],
             u2.ram_array[4], // R4 added for full visibility of the loop accumulator
             alu_op,
             br_sel,
             pc_write,
             pc_sel);
  end // prints every time any monitored signal changes value

endmodule