// ECE:3350 SISC processor project
// main SISC module, part 1

`timescale 1ns/100ps  

module sisc (clk, rst_f, ir);

  input clk, rst_f;
  input [31:0] ir;

// declare all internal wires here
  wire rf_we;              // register file write enable
  wire wb_sel;             // writeback mux select
  wire [3:0] alu_op;       // selects ALU operation
  wire [31:0] rsa;         // source register A value read from the register file
  wire [31:0] rsb;         // source register B value read from the register file
  wire [31:0] alu_result;  // ALU output
  wire [31:0] write_data;  // Data presented to the register file write_data input
  wire [3:0] alu_stat;     // New status bits generated by the ALU
  wire [3:0] stat_en;      // Per-bit enable lines for updating the status register
  wire [3:0] stat_out;     // Current status register output


// component instantiation goes here
  ctrl my_ctrl (clk, rst_f, ir[31:28], ir[27:24], stat_out, rf_we, alu_op, wb_sel);
  rf my_rf (clk, ir[19:16], ir[15:12], ir[23:20], write_data, rf_we, rsa, rsb);
  alu my_alu (clk, rsa, rsb, ir[15:0], stat_out[3], alu_op, ir[27:24], alu_result, alu_stat, stat_en);
  statreg my_statreg (clk, alu_stat, stat_en, stat_out);
  mux32 my_mux (alu_result, 32'h00000000, wb_sel, write_data);


  initial begin
  
// put a $monitor statement here.  
    $monitor($time," IR=%h R1=%h R2=%h R3=%h R4=%h R5=%h STAT=%b ALU_OP=%h WB_SEL=%b RF_WE=%b WRITE_DATA=%h",
             ir,
             my_rf.ram_array[1],
             my_rf.ram_array[2],
             my_rf.ram_array[3],
             my_rf.ram_array[4],
             my_rf.ram_array[5],
             stat_out,
             alu_op,
             wb_sel,
             rf_we,
             write_data);
  end //Fairely self exclamatory we are just using $monitor to print the values

endmodule